server:
  port: 9296

spring:
  application:
    name: WEBNET-CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/abammeke/webnet-config-server.git
          clone-on-start: true
          username: abammeke
          password: A@yobami147